wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.10
    cli_version: 0.14.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1681911800.906485
    t:
      1:
      - 55
      3:
      - 23
      4: 3.9.10
      5: 0.14.2
      8:
      - 1
      - 8
